# Generated by Django 3.1.7 on 2021-04-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0002_auto_20210407_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superhero',
            old_name='catch_phrase',
            new_name='catchphrase',
        ),
    ]
