# Generated by Django 3.1.7 on 2021-04-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0003_auto_20210407_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superhero',
            old_name='catchphrase',
            new_name='catch_phrase',
        ),
    ]
